### ISSUE TITLE
Panic seen when ssh collect used against AWSE nodes with no sudo user

### ISSUE THREAD

**Issue by markcurtis1970** [dremio/dremio-diagnostic-collector#103]
The following panic stack is seen when running a ssh collect against a AWSE node and not providing the sudo user

The reason seems to be because the PID is not obtained - the dremio process on AWSE nodes runs as the `dremio` users whereas the typical login shell is with the ec2-user. Therefore the `jps` command returns no PID for dremio. This might be at the root cause of this panic.

We should handle this condition and fail is this is indeed the root cause

### Error:

```
HOST 18.203.223.41 - SIGQUIT: quit
HOST 18.203.223.41 - PC=0x46b181 m=0 sigcode=0
HOST 18.203.223.41 -
HOST 18.203.223.41 - goroutine 0 [idle]:
HOST 18.203.223.41 - runtime.futex()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/sys_linux_amd64.s:554 +0x21 fp=0x7fff1929c258 sp=0x7fff1929c250 pc=0x46b181
HOST 18.203.223.41 - runtime.futexsleep(0x10023ca6689?, 0x1929c2d8?, 0x445d4c?)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/os_linux.go:69 +0x36 fp=0x7fff1929c2a8 sp=0x7fff1929c258 pc=0x432e56
HOST 18.203.223.41 - runtime.notesleep(0xd5d248)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/lock_futex.go:160 +0x87 fp=0x7fff1929c2e0 sp=0x7fff1929c2a8 pc=0x40db07
HOST 18.203.223.41 - runtime.mPark(...)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:1531
HOST 18.203.223.41 - runtime.stopm()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:2335 +0x8c fp=0x7fff1929c310 sp=0x7fff1929c2e0 pc=0x43d7ac
HOST 18.203.223.41 - runtime.findRunnable()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:3025 +0xabc fp=0x7fff1929c418 sp=0x7fff1929c310 pc=0x43f05c
HOST 18.203.223.41 - runtime.schedule()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:3378 +0xb1 fp=0x7fff1929c450 sp=0x7fff1929c418 pc=0x43fe91
HOST 18.203.223.41 - runtime.park_m(0xc002088000?)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:3529 +0x12d fp=0x7fff1929c480 sp=0x7fff1929c450 pc=0x4403ad
HOST 18.203.223.41 - runtime.mcall()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/asm_amd64.s:452 +0x43 fp=0x7fff1929c490 sp=0x7fff1929c480 pc=0x467043
HOST 18.203.223.41 -
HOST 18.203.223.41 - goroutine 1 [semacquire]:
HOST 18.203.223.41 - runtime.gopark(0xb44887?, 0x49?, 0x60?, 0x40?, 0xc000111608?)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001115c8 sp=0xc0001115a8 pc=0x4398d6
HOST 18.203.223.41 - runtime.goparkunlock(...)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:387
HOST 18.203.223.41 - runtime.semacquire1(0xc000024548, 0x10?, 0x1, 0x0, 0x51?)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/sema.go:160 +0x20f fp=0xc000111630 sp=0xc0001115c8 pc=0x44a68f
HOST 18.203.223.41 - sync.runtime_Semacquire(0xc002106060?)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/sema.go:62 +0x27 fp=0xc000111668 sp=0xc000111630 pc=0x465307
HOST 18.203.223.41 - sync.(*WaitGroup).Wait(0x0?)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/sync/waitgroup.go:116 +0x4b fp=0xc000111690 sp=0xc000111668 pc=0x48324b
HOST 18.203.223.41 - github.com/dremio/dremio-diagnostic-collector/cmd/local/threading.(*ThreadPool).ProcessAndWait(0xc000024540)
HOST 18.203.223.41 -    /jenkins/workspace/dremio-diagnostic-collector-release/cmd/local/threading/thread_pool.go:104 +0x12f fp=0xc0001116f8 sp=0xc000111690 pc=0x7936af
HOST 18.203.223.41 - github.com/dremio/dremio-diagnostic-collector/cmd/local.collect(0xc0001541c0)
HOST 18.203.223.41 -    /jenkins/workspace/dremio-diagnostic-collector-release/cmd/local/local.go:234 +0xdb5 fp=0xc000111828 sp=0xc0001116f8 pc=0x7c8cb5
HOST 18.203.223.41 - github.com/dremio/dremio-diagnostic-collector/cmd/local.Execute({0xc0000304a0, 0x0, 0x2}, 0x0?)
HOST 18.203.223.41 -    /jenkins/workspace/dremio-diagnostic-collector-release/cmd/local/local.go:372 +0x218 fp=0xc000111950 sp=0xc000111828 pc=0x7ca138
HOST 18.203.223.41 - github.com/dremio/dremio-diagnostic-collector/cmd/local.glob..func1(0xd53460?, {0xc0000304a0, 0x0, 0x2})
HOST 18.203.223.41 -    /jenkins/workspace/dremio-diagnostic-collector-release/cmd/local/local.go:350 +0xdb fp=0xc000111ae0 sp=0xc000111950 pc=0x7c9b5b
HOST 18.203.223.41 - github.com/spf13/cobra.(*Command).execute(0xd53460, {0xc000030480, 0x2, 0x2})
HOST 18.203.223.41 -    /jenkins/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847 fp=0xc000111c18 sp=0xc000111ae0 pc=0x5a5787
HOST 18.203.223.41 - github.com/spf13/cobra.(*Command).ExecuteC(0xd52ea0)
HOST 18.203.223.41 -    /jenkins/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd fp=0xc000111cd0 sp=0xc000111c18 pc=0x5a601d
HOST 18.203.223.41 - github.com/spf13/cobra.(*Command).Execute(...)
HOST 18.203.223.41 -    /jenkins/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
HOST 18.203.223.41 - github.com/dremio/dremio-diagnostic-collector/cmd.Execute({0xc000024080, 0x4, 0x4})
HOST 18.203.223.41 -    /jenkins/workspace/dremio-diagnostic-collector-release/cmd/root.go:183 +0x645 fp=0xc000111f48 sp=0xc000111cd0 pc=0x7e42e5
HOST 18.203.223.41 - main.main()
HOST 18.203.223.41 -    /jenkins/workspace/dremio-diagnostic-collector-release/main.go:34 +0x5a fp=0xc000111f80 sp=0xc000111f48 pc=0x7e4f3a
HOST 18.203.223.41 - runtime.main()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:250 +0x207 fp=0xc000111fe0 sp=0xc000111f80 pc=0x4394a7
HOST 18.203.223.41 - runtime.goexit()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000111fe8 sp=0xc000111fe0 pc=0x469281
HOST 18.203.223.41 -
HOST 18.203.223.41 - goroutine 2 [force gc (idle)]:
HOST 18.203.223.41 - runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:381 +0xd6 fp=0xc000044fb0 sp=0xc000044f90 pc=0x4398d6
HOST 18.203.223.41 - runtime.goparkunlock(...)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:387
HOST 18.203.223.41 - runtime.forcegchelper()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:305 +0xb0 fp=0xc000044fe0 sp=0xc000044fb0 pc=0x439710
HOST 18.203.223.41 - runtime.goexit()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000044fe8 sp=0xc000044fe0 pc=0x469281
HOST 18.203.223.41 - created by runtime.init.6
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:293 +0x25
HOST 18.203.223.41 -
HOST 18.203.223.41 - goroutine 3 [GC sweep wait]:
HOST 18.203.223.41 - runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:381 +0xd6 fp=0xc000045780 sp=0xc000045760 pc=0x4398d6
HOST 18.203.223.41 - runtime.goparkunlock(...)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:387
HOST 18.203.223.41 - runtime.bgsweep(0x0?)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/mgcsweep.go:319 +0xde fp=0xc0000457c8 sp=0xc000045780 pc=0x425a7e
HOST 18.203.223.41 - runtime.gcenable.func1()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000457e0 sp=0xc0000457c8 pc=0x41ace6
HOST 18.203.223.41 - runtime.goexit()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000457e8 sp=0xc0000457e0 pc=0x469281
HOST 18.203.223.41 - created by runtime.gcenable
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/mgc.go:178 +0x6b
HOST 18.203.223.41 -
HOST 18.203.223.41 - goroutine 4 [GC scavenge wait]:
HOST 18.203.223.41 - runtime.gopark(0xc00006c000?, 0xac0210?, 0x0?, 0x0?, 0x0?)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:381 +0xd6 fp=0xc000045f70 sp=0xc000045f50 pc=0x4398d6
HOST 18.203.223.41 - runtime.goparkunlock(...)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:387
HOST 18.203.223.41 - runtime.(*scavengerState).park(0xd5c760)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000045fa0 sp=0xc000045f70 pc=0x423953
HOST 18.203.223.41 - runtime.bgscavenge(0x0?)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/mgcscavenge.go:633 +0x65 fp=0xc000045fc8 sp=0xc000045fa0 pc=0x423f45
HOST 18.203.223.41 - runtime.gcenable.func2()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/mgc.go:179 +0x26 fp=0xc000045fe0 sp=0xc000045fc8 pc=0x41ac86
HOST 18.203.223.41 - runtime.goexit()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000045fe8 sp=0xc000045fe0 pc=0x469281
HOST 18.203.223.41 - created by runtime.gcenable
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/mgc.go:179 +0xaa
HOST 18.203.223.41 -
HOST 18.203.223.41 - goroutine 5 [finalizer wait]:
HOST 18.203.223.41 - runtime.gopark(0x0?, 0xa57338?, 0x40?, 0x60?, 0x2000000020?)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:381 +0xd6 fp=0xc000044628 sp=0xc000044608 pc=0x4398d6
HOST 18.203.223.41 - runtime.runfinq()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000447e0 sp=0xc000044628 pc=0x419d27
HOST 18.203.223.41 - runtime.goexit()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000447e8 sp=0xc0000447e0 pc=0x469281
HOST 18.203.223.41 - created by runtime.createfing
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/mfinal.go:163 +0x45
HOST 18.203.223.41 -
HOST 18.203.223.41 - goroutine 10 [GC worker (idle)]:
HOST 18.203.223.41 - runtime.gopark(0xb2326a3e8888?, 0x0?, 0x0?, 0x0?, 0xc00006ec00?)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:381 +0xd6 fp=0xc000046f50 sp=0xc000046f30 pc=0x4398d6
HOST 18.203.223.41 - runtime.gcBgMarkWorker()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000046fe0 sp=0xc000046f50 pc=0x41ca51
HOST 18.203.223.41 - runtime.goexit()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000046fe8 sp=0xc000046fe0 pc=0x469281
HOST 18.203.223.41 - created by runtime.gcBgMarkStartWorkers
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/mgc.go:1199 +0x25
HOST 18.203.223.41 -
HOST 18.203.223.41 - goroutine 18 [GC worker (idle)]:
HOST 18.203.223.41 - runtime.gopark(0xb2326a3fb806?, 0x3?, 0x84?, 0x2d?, 0xc00006e660?)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:381 +0xd6 fp=0xc000046750 sp=0xc000046730 pc=0x4398d6
HOST 18.203.223.41 - runtime.gcBgMarkWorker()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000467e0 sp=0xc000046750 pc=0x41ca51
HOST 18.203.223.41 - runtime.goexit()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000467e8 sp=0xc0000467e0 pc=0x469281
HOST 18.203.223.41 - created by runtime.gcBgMarkStartWorkers
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/mgc.go:1199 +0x25
HOST 18.203.223.41 -
HOST 18.203.223.41 - goroutine 19 [GC worker (idle)]:
HOST 18.203.223.41 - runtime.gopark(0xb2326a3e5d98?, 0x3?, 0xac?, 0xee?, 0x0?)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:381 +0xd6 fp=0xc000040750 sp=0xc000040730 pc=0x4398d6
HOST 18.203.223.41 - runtime.gcBgMarkWorker()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000407e0 sp=0xc000040750 pc=0x41ca51
HOST 18.203.223.41 - runtime.goexit()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000407e8 sp=0xc0000407e0 pc=0x469281
HOST 18.203.223.41 - created by runtime.gcBgMarkStartWorkers
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/mgc.go:1199 +0x25
HOST 18.203.223.41 -
HOST 18.203.223.41 - goroutine 34 [GC worker (idle)]:
HOST 18.203.223.41 - runtime.gopark(0xb2326a3c9d64?, 0x0?, 0x0?, 0x0?, 0x0?)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:381 +0xd6 fp=0xc00208e750 sp=0xc00208e730 pc=0x4398d6
HOST 18.203.223.41 - runtime.gcBgMarkWorker()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00208e7e0 sp=0xc00208e750 pc=0x41ca51
HOST 18.203.223.41 - runtime.goexit()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00208e7e8 sp=0xc00208e7e0 pc=0x469281
HOST 18.203.223.41 - created by runtime.gcBgMarkStartWorkers
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/mgc.go:1199 +0x25
HOST 18.203.223.41 -
HOST 18.203.223.41 - goroutine 50 [chan receive]:
HOST 18.203.223.41 - runtime.gopark(0x0?, 0x4fb240?, 0xc0?, 0x88?, 0xc002096e98?)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:381 +0xd6 fp=0xc002096e90 sp=0xc002096e70 pc=0x4398d6
HOST 18.203.223.41 - runtime.chanrecv(0xc00006ec60, 0xc002096f80, 0x1)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/chan.go:583 +0x49d fp=0xc002096f20 sp=0xc002096e90 pc=0x4089bd
HOST 18.203.223.41 - runtime.chanrecv2(0x8a224d?, 0x0?)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/chan.go:447 +0x18 fp=0xc002096f48 sp=0xc002096f20 pc=0x4084f8
HOST 18.203.223.41 - github.com/dremio/dremio-diagnostic-collector/cmd/local/threading.(*ThreadPool).worker(0xc000024540)
HOST 18.203.223.41 -    /jenkins/workspace/dremio-diagnostic-collector-release/cmd/local/threading/thread_pool.go:75 +0x57 fp=0xc002096fc8 sp=0xc002096f48 pc=0x7933d7
HOST 18.203.223.41 - github.com/dremio/dremio-diagnostic-collector/cmd/local/threading.(*ThreadPool).ProcessAndWait.func1()
HOST 18.203.223.41 -    /jenkins/workspace/dremio-diagnostic-collector-release/cmd/local/threading/thread_pool.go:101 +0x26 fp=0xc002096fe0 sp=0xc002096fc8 pc=0x7937c6
HOST 18.203.223.41 - runtime.goexit()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc002096fe8 sp=0xc002096fe0 pc=0x469281
HOST 18.203.223.41 - created by github.com/dremio/dremio-diagnostic-collector/cmd/local/threading.(*ThreadPool).ProcessAndWait
HOST 18.203.223.41 -    /jenkins/workspace/dremio-diagnostic-collector-release/cmd/local/threading/thread_pool.go:101 +0xc5
HOST 18.203.223.41 -
HOST 18.203.223.41 - goroutine 51 [sleep]:
HOST 18.203.223.41 - runtime.gopark(0xb2326c682eec?, 0x2?, 0xf8?, 0xa8?, 0x3?)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:381 +0xd6 fp=0xc000115d30 sp=0xc000115d10 pc=0x4398d6
HOST 18.203.223.41 - time.Sleep(0x3b9aca00)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/time.go:195 +0x135 fp=0xc000115d70 sp=0xc000115d30 pc=0x4660f5
HOST 18.203.223.41 - github.com/dremio/dremio-diagnostic-collector/cmd/local/jvmcollect.(*DateTimeTicker).WaitSeconds(0xc000025280?, 0xc12d613f77d2cec8?)
HOST 18.203.223.41 -    /jenkins/workspace/dremio-diagnostic-collector-release/cmd/local/jvmcollect/ttopcollect.go:142 +0x25 fp=0xc000115d88 sp=0xc000115d70 pc=0x7b5785
HOST 18.203.223.41 - github.com/dremio/dremio-diagnostic-collector/cmd/local/jvmcollect.OnLoop({0xc000115ef0?, 0x40876e?}, 0x3c, {0xc00209a280, 0x47}, {0xac5ab8, 0xc000025280}, {0xac4100, 0xd8b970})
HOST 18.203.223.41 -    /jenkins/workspace/dremio-diagnostic-collector-release/cmd/local/jvmcollect/ttopcollect.go:162 +0x11c fp=0xc000115e80 sp=0xc000115d88 pc=0x7b5a3c
HOST 18.203.223.41 - github.com/dremio/dremio-diagnostic-collector/cmd/local/jvmcollect.RunTtopCollect(0xc0001541c0)
HOST 18.203.223.41 -    /jenkins/workspace/dremio-diagnostic-collector-release/cmd/local/jvmcollect/ttopcollect.go:151 +0x134 fp=0xc000115f30 sp=0xc000115e80 pc=0x7b58f4
HOST 18.203.223.41 - github.com/dremio/dremio-diagnostic-collector/cmd/local.collect.func7()
HOST 18.203.223.41 -    /jenkins/workspace/dremio-diagnostic-collector-release/cmd/local/local.go:101 +0x22 fp=0xc000115f48 sp=0xc000115f30 pc=0x7c8f02
HOST 18.203.223.41 - github.com/dremio/dremio-diagnostic-collector/cmd/local/threading.(*ThreadPool).worker(0xc000024540)
HOST 18.203.223.41 -    /jenkins/workspace/dremio-diagnostic-collector-release/cmd/local/threading/thread_pool.go:76 +0x72 fp=0xc000115fc8 sp=0xc000115f48 pc=0x7933f2
HOST 18.203.223.41 - github.com/dremio/dremio-diagnostic-collector/cmd/local/threading.(*ThreadPool).ProcessAndWait.func1()
HOST 18.203.223.41 -    /jenkins/workspace/dremio-diagnostic-collector-release/cmd/local/threading/thread_pool.go:101 +0x26 fp=0xc000115fe0 sp=0xc000115fc8 pc=0x7937c6
HOST 18.203.223.41 - runtime.goexit()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000115fe8 sp=0xc000115fe0 pc=0x469281
HOST 18.203.223.41 - created by github.com/dremio/dremio-diagnostic-collector/cmd/local/threading.(*ThreadPool).ProcessAndWait
HOST 18.203.223.41 -    /jenkins/workspace/dremio-diagnostic-collector-release/cmd/local/threading/thread_pool.go:101 +0xc5
HOST 18.203.223.41 -
HOST 18.203.223.41 - goroutine 35 [runnable]:
HOST 18.203.223.41 - syscall.Syscall(0xc00208ac70?, 0x43?, 0x4d67b2?, 0x7ffff800000?)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/syscall/syscall_linux.go:69 +0x27 fp=0xc00208ac90 sp=0xc00208ac20 pc=0x4bc0c7
HOST 18.203.223.41 - syscall.read(0xc0020a0d20?, {0xc002127335?, 0xc00208ad01?, 0x418813?})
HOST 18.203.223.41 -    /jenkins/workspace/go/src/syscall/zsyscall_linux_amd64.go:711 +0x45 fp=0xc00208acd0 sp=0xc00208ac90 pc=0x4ba005
HOST 18.203.223.41 - syscall.Read(...)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/syscall/syscall_unix.go:178
HOST 18.203.223.41 - internal/poll.ignoringEINTRIO(...)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/internal/poll/fd_unix.go:794
HOST 18.203.223.41 - internal/poll.(*FD).Read(0xc0020a0d20?, {0xc002127335?, 0xccb?, 0xccb?})
HOST 18.203.223.41 -    /jenkins/workspace/go/src/internal/poll/fd_unix.go:163 +0x2ce fp=0xc00208ad68 sp=0xc00208acd0 pc=0x4d7d0e
HOST 18.203.223.41 - os.(*File).read(...)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/os/file_posix.go:31
HOST 18.203.223.41 - os.(*File).Read(0xc00209e118, {0xc002127335?, 0xccc?, 0x0?})
HOST 18.203.223.41 -    /jenkins/workspace/go/src/os/file.go:118 +0x5e fp=0xc00208adc0 sp=0xc00208ad68 pc=0x4e335e
HOST 18.203.223.41 - bufio.(*Scanner).Scan(0xc00208af50)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/bufio/scan.go:214 +0x876 fp=0xc00208ae98 sp=0xc00208adc0 pc=0x556cd6
HOST 18.203.223.41 - github.com/dremio/dremio-diagnostic-collector/cmd/local/jvmcollect.(*Ttop).StartTtop.func1()
HOST 18.203.223.41 -    /jenkins/workspace/dremio-diagnostic-collector-release/cmd/local/jvmcollect/ttopcollect.go:98 +0xb3 fp=0xc00208afe0 sp=0xc00208ae98 pc=0x7b50b3
HOST 18.203.223.41 - runtime.goexit()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00208afe8 sp=0xc00208afe0 pc=0x469281
HOST 18.203.223.41 - created by github.com/dremio/dremio-diagnostic-collector/cmd/local/jvmcollect.(*Ttop).StartTtop
HOST 18.203.223.41 -    /jenkins/workspace/dremio-diagnostic-collector-release/cmd/local/jvmcollect/ttopcollect.go:96 +0x61f
HOST 18.203.223.41 -
HOST 18.203.223.41 - goroutine 36 [IO wait]:
HOST 18.203.223.41 - runtime.gopark(0x2000?, 0xb?, 0x0?, 0x0?, 0xa?)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/proc.go:381 +0xd6 fp=0xc00208b450 sp=0xc00208b430 pc=0x4398d6
HOST 18.203.223.41 - runtime.netpollblock(0x4ba005?, 0x40528f?, 0x0?)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/netpoll.go:527 +0xf7 fp=0xc00208b488 sp=0xc00208b450 pc=0x432177
HOST 18.203.223.41 - internal/poll.runtime_pollWait(0x7fb0b92adc28, 0x72)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/netpoll.go:306 +0x89 fp=0xc00208b4a8 sp=0xc00208b488 pc=0x463949
HOST 18.203.223.41 - internal/poll.(*pollDesc).wait(0xc0020a0de0?, 0xc00008e000?, 0x1)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/internal/poll/fd_poll_runtime.go:84 +0x32 fp=0xc00208b4d0 sp=0xc00208b4a8 pc=0x4d68f2
HOST 18.203.223.41 - internal/poll.(*pollDesc).waitRead(...)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/internal/poll/fd_poll_runtime.go:89
HOST 18.203.223.41 - internal/poll.(*FD).Read(0xc0020a0de0, {0xc00008e000, 0x1000, 0x1000})
HOST 18.203.223.41 -    /jenkins/workspace/go/src/internal/poll/fd_unix.go:167 +0x299 fp=0xc00208b568 sp=0xc00208b4d0 pc=0x4d7cd9
HOST 18.203.223.41 - os.(*File).read(...)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/os/file_posix.go:31
HOST 18.203.223.41 - os.(*File).Read(0xc00209e128, {0xc00008e000?, 0x0?, 0x0?})
HOST 18.203.223.41 -    /jenkins/workspace/go/src/os/file.go:118 +0x5e fp=0xc00208b5c0 sp=0xc00208b568 pc=0x4e335e
HOST 18.203.223.41 - bufio.(*Scanner).Scan(0xc00208b750)
HOST 18.203.223.41 -    /jenkins/workspace/go/src/bufio/scan.go:214 +0x876 fp=0xc00208b698 sp=0xc00208b5c0 pc=0x556cd6
HOST 18.203.223.41 - github.com/dremio/dremio-diagnostic-collector/cmd/local/jvmcollect.(*Ttop).StartTtop.func2()
HOST 18.203.223.41 -    /jenkins/workspace/dremio-diagnostic-collector-release/cmd/local/jvmcollect/ttopcollect.go:107 +0xb3 fp=0xc00208b7e0 sp=0xc00208b698 pc=0x7b4e53
HOST 18.203.223.41 - runtime.goexit()
HOST 18.203.223.41 -    /jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00208b7e8 sp=0xc00208b7e0 pc=0x469281
HOST 18.203.223.41 - created by github.com/dremio/dremio-diagnostic-collector/cmd/local/jvmcollect.(*Ttop).StartTtop
HOST 18.203.223.41 -    /jenkins/workspace/dremio-diagnostic-collector-release/cmd/local/jvmcollect/ttopcollect.go:105 +0x68a
HOST 18.203.223.41 -
HOST 18.203.223.41 - rax    0xca
HOST 18.203.223.41 - rbx    0x0
HOST 18.203.223.41 - rcx    0x46b183
HOST 18.203.223.41 - rdx    0x0
HOST 18.203.223.41 - rdi    0xd5d248
HOST 18.203.223.41 - rsi    0x80
HOST 18.203.223.41 - rbp    0x7fff1929c298
HOST 18.203.223.41 - rsp    0x7fff1929c250
HOST 18.203.223.41 - r8     0x0
HOST 18.203.223.41 - r9     0x0
HOST 18.203.223.41 - r10    0x0
HOST 18.203.223.41 - r11    0x286
HOST 18.203.223.41 - r12    0x0
HOST 18.203.223.41 - r13    0x2
HOST 18.203.223.41 - r14    0xd5cb20
HOST 18.203.223.41 - r15    0x200000
HOST 18.203.223.41 - rip    0x46b181
HOST 18.203.223.41 - rflags 0x286
HOST 18.203.223.41 - cs     0x33
HOST 18.203.223.41 - fs     0x0
HOST 18.203.223.41 - gs     0x0
ERROR: 2023/08/10 17:17:01 sudo.go:34: host 18.203.223.41 failed to run command with error 'unable to start command 'ssh -i /Users/mc/Support/mc-ssh-ireland.cer -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@18.203.223.41 /tmp/ddc/ddc local-collect --tarball-out-dir /tmp/ddc' due to error 'exit status 2''
```

### Repro

Run a ddc collection against your AWSE node like so

```
ddc -c 100.1.2.3 -e 100.1.2.4 --ssh-key ~/my-key --ssh-user ec2-user
```

A correct AWSE collection via ssh would include the sudo use:

```
ddc -c 100.1.2.3 -e 100.1.2.4 --ssh-key ~/my-key --ssh-user ec2-user --sudo-user dremio
```

**Comment by rsvihladremio** [comment]
yeah this used to fail gracefully not sure why it no longer does. This is just a reporting/error handling bug

**Comment by markcurtis1970** [comment]
Ok figured out this seems to be coming from when we run ttop collect. If I switch this off when running it does not repro

```
collect-ttop: false
```
