### ISSUE TITLE
Collecting job profiles with PAT throws error

### ISSUE THREAD

**Issue by markcurtis1970** [dremio/dremio-diagnostic-collector#16]
Saw the following error on a call today with a customer when using a PAT

```
DEBUG: 2023/06/07 12:23:14 local.go:1509: Requesting http://localhost:9047/apiv2/login
2023/06/07 12:23:14 Attempting to open queries.json file /tmp/ddc/20230607-122214/queries/ip-x.x.x.queries.2023-05-10.0.json.gz
panic: interface conversion: interface {} is nil, not float64

goroutine 1 [running]:
github.com/rsvihladremio/dremio-diagnostic-collector/cmd/local/queriesjson.parseLine({0xc00338a000, 0x1d7}, 0x80000000000?)
        /Users/ryan.svihla/Documents/GitHub/dremio-diagnostic-collector/cmd/local/queriesjson/queries.go:146 +0x494
github.com/rsvihladremio/dremio-diagnostic-collector/cmd/local/queriesjson.ReadGzFile({0xc00327a070, 0x6b})
        /Users/ryan.svihla/Documents/GitHub/dremio-diagnostic-collector/cmd/local/queriesjson/queries.go:103 +0x2ef
github.com/rsvihladremio/dremio-diagnostic-collector/cmd/local/queriesjson.CollectQueriesJSON({0xc003278400?, 0x2e, 0x452f09?})
        /Users/ryan.svihla/Documents/GitHub/dremio-diagnostic-collector/cmd/local/queriesjson/queries.go:223 +0x30f
github.com/rsvihladremio/dremio-diagnostic-collector/cmd.runCollectJobProfiles()
        /Users/ryan.svihla/Documents/GitHub/dremio-diagnostic-collector/cmd/local.go:827 +0x328
github.com/rsvihladremio/dremio-diagnostic-collector/cmd.collect(0x2)
        /Users/ryan.svihla/Documents/GitHub/dremio-diagnostic-collector/cmd/local.go:471 +0x97d
github.com/rsvihladremio/dremio-diagnostic-collector/cmd.glob..func1(0xc3ddc0?, {0x8d3f2d?, 0x0?, 0x0?})
        /Users/ryan.svihla/Documents/GitHub/dremio-diagnostic-collector/cmd/local.go:1268 +0x1516
github.com/spf13/cobra.(*Command).execute(0xc3ddc0, {0xc766c8, 0x0, 0x0})
        /Users/ryan.svihla/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc3e0a0)
        /Users/ryan.svihla/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/ryan.svihla/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/rsvihladremio/dremio-diagnostic-collector/cmd.Execute()
        /Users/ryan.svihla/Documents/GitHub/dremio-diagnostic-collector/cmd/root.go:144 +0xaf1
main.main()
        /Users/ryan.svihla/Documents/GitHub/dremio-diagnostic-collector/main.go:21 +0x17
```

I'll send the diag directly rather than post here

**Comment by rsvihladremio** [comment]
So if you follow the stack trace

```
github.com/rsvihladremio/dremio-diagnostic-collector/cmd/local/queriesjson.parseLine({0xc00338a000, 0x1d7}, 0x80000000000?)
        /Users/ryan.svihla/Documents/GitHub/dremio-diagnostic-collector/cmd/local/queriesjson/queries.go:146 +0x494

```
and go to that commit so do the following:

- git checkout v0.3.1
- vim cmd/local/queries/queries.json
-  navigate to line 146

you will see

<img width="571" alt="Capture d’écran 2023-06-08 à 07 05 56" src="https://github.com/dremio/dremio-diagnostic-collector/assets/105286284/d0e92a01-d8e1-4792-b65d-ff1da592f033">

which when reading that error 

```
panic: interface conversion: interface {} is nil, not float64
```

we can see that there was no value for queryCost in that job Profile. 

If we go to the same logical line on the `main` branch, we can see that it properly handles this situation now 

<img width="654" alt="Capture d’écran 2023-06-08 à 07 12 49" src="https://github.com/dremio/dremio-diagnostic-collector/assets/105286284/61a284f0-3966-478e-b3ef-a48c24fad037">

and was fixed by @mxmarg yesterday in this commit 

<img width="1395" alt="Capture d’écran 2023-06-08 à 07 13 46" src="https://github.com/dremio/dremio-diagnostic-collector/assets/105286284/bfd5690b-352b-4814-b7a7-68e54b823153">

Since this is already done but not yet released, I will shift the remaining features for 0.3.2 over to 0.4.0 and leave 0.3.x as a bug-fix branch, but nothing to do here.
