### ISSUE TITLE
build breaks with weird errors 

### ISSUE THREAD

**Issue by rsvihladremio** [dremio/dremio-diagnostic-collector#161]
Since we get new containers on every build I am not sure what this could be but it happens consistently. Possible ideas

1. possibly related to the clear terminal code we added and the jenkins build env
2. could be a combination of features implemented and go version try new go versions

```
x.xxxSIGQUIT: quit
PC=0x4aa621 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex()
	/jenkins/workspace/go/src/runtime/sys_linux_amd64.s:554 +0x21 fp=0x7ffc8b95b768 sp=0x7ffc8b95b760 pc=0x4aa621
runtime.futexsleep(0x4aa213?, 0x8b95b7e8?, 0x47f12c?)
	/jenkins/workspace/go/src/runtime/os_linux.go:69 +0x36 fp=0x7ffc8b95b7b8 sp=0x7ffc8b95b768 pc=0x46bc56
runtime.notesleep(0x10bb608)
	/jenkins/workspace/go/src/runtime/lock_futex.go:160 +0x87 fp=0x7ffc8b95b7f0 sp=0x7ffc8b95b7b8 pc=0x4447e7
runtime.mPark(...)
	/jenkins/workspace/go/src/runtime/proc.go:1531
runtime.stopm()
	/jenkins/workspace/go/src/runtime/proc.go:2335 +0x8c fp=0x7ffc8b95b820 sp=0x7ffc8b95b7f0 pc=0x47688c
runtime.findRunnable()
	/jenkins/workspace/go/src/runtime/proc.go:3025 +0xabc fp=0x7ffc8b95b928 sp=0x7ffc8b95b820 pc=0x47813c
runtime.schedule()
	/jenkins/workspace/go/src/runtime/proc.go:3378 +0xb1 fp=0x7ffc8b95b960 sp=0x7ffc8b95b928 pc=0x478f71
runtime.park_m(0xc00008a340?)
	/jenkins/workspace/go/src/runtime/proc.go:3529 +0x12d fp=0x7ffc8b95b990 sp=0x7ffc8b95b960 pc=0x47948d
runtime.mcall()
	/jenkins/workspace/go/src/runtime/asm_amd64.s:452 +0x43 fp=0x7ffc8b95b9a0 sp=0x7ffc8b95b990 pc=0x4a5da3

goroutine 1 [chan receive]:
runtime.gopark(0xc000187728?, 0x445f15?, 0x80?, 0x18?, 0x0?)
	/jenkins/workspace/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001876a8 sp=0xc000187688 pc=0x472976
runtime.chanrecv(0xc000188230, 0xc0001877a6, 0x1)
	/jenkins/workspace/go/src/runtime/chan.go:583 +0x42e fp=0xc000187738 sp=0xc0001876a8 pc=0x43e8ce
runtime.chanrecv1(0x10ba400?, 0xadbc80?)
	/jenkins/workspace/go/src/runtime/chan.go:442 +0x18 fp=0xc000187760 sp=0xc000187738 pc=0x43e438
testing.(*T).Run(0xc00010d380, {0xb6fed5, 0xc}, 0xd1db10)
	/jenkins/workspace/go/src/testing/testing.go:1630 +0x82e fp=0xc0001878a0 sp=0xc000187760 pc=0x634c0e
testing.runTests.func1(0x0?)
	/jenkins/workspace/go/src/testing/testing.go:2036 +0x8e fp=0xc0001878f8 sp=0xc0001878a0 pc=0x63876e
testing.tRunner(0xc00010d380, 0xc000187b40)
	/jenkins/workspace/go/src/testing/testing.go:1576 +0x217 fp=0xc000187a00 sp=0xc0001878f8 pc=0x633397
testing.runTests(0xc00018e0a0?, {0x10a9980, 0x1, 0x1}, {0x1c?, 0x4a9779?, 0x10baaa0?})
	/jenkins/workspace/go/src/testing/testing.go:2034 +0x87d fp=0xc000187b70 sp=0xc000187a00 pc=0x6385bd
testing.(*M).Run(0xc00018e0a0)
	/jenkins/workspace/go/src/testing/testing.go:1906 +0xb45 fp=0xc000187ed0 sp=0xc000187b70 pc=0x635e25
main.main()
	_testmain.go:80 +0x2fd fp=0xc000187f80 sp=0xc000187ed0 pc=0xaa70fd
runtime.main()
	/jenkins/workspace/go/src/runtime/proc.go:250 +0x207 fp=0xc000187fe0 sp=0xc000187f80 pc=0x472527
runtime.goexit()
	/jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000187fe8 sp=0xc000187fe0 pc=0x4a7fe1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x10bb4c0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/jenkins/workspace/go/src/runtime/proc.go:381 +0xd6 fp=0xc0000527b0 sp=0xc000052790 pc=0x472976
runtime.goparkunlock(...)
	/jenkins/workspace/go/src/runtime/proc.go:387
runtime.forcegchelper()
	/jenkins/workspace/go/src/runtime/proc.go:305 +0xb0 fp=0xc0000527e0 sp=0xc0000527b0 pc=0x4727b0
runtime.goexit()
	/jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000527e8 sp=0xc0000527e0 pc=0x4a7fe1
created by runtime.init.6
	/jenkins/workspace/go/src/runtime/proc.go:293 +0x25

goroutine 18 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/jenkins/workspace/go/src/runtime/proc.go:381 +0xd6 fp=0xc000060f80 sp=0xc000060f60 pc=0x472976
runtime.goparkunlock(...)
	/jenkins/workspace/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/jenkins/workspace/go/src/runtime/mgcsweep.go:319 +0xde fp=0xc000060fc8 sp=0xc000060f80 pc=0x45cbfe
runtime.gcenable.func1()
	/jenkins/workspace/go/src/runtime/mgc.go:178 +0x26 fp=0xc000060fe0 sp=0xc000060fc8 pc=0x451e86
runtime.goexit()
	/jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000060fe8 sp=0xc000060fe0 pc=0x4a7fe1
created by runtime.gcenable
	/jenkins/workspace/go/src/runtime/mgc.go:178 +0x6b

goroutine 19 [GC scavenge wait]:
runtime.gopark(0xc000096000?, 0xdb9be8?, 0x0?, 0x0?, 0x0?)
	/jenkins/workspace/go/src/runtime/proc.go:381 +0xd6 fp=0xc000066f70 sp=0xc000066f50 pc=0x472976
runtime.goparkunlock(...)
	/jenkins/workspace/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x10bab20)
	/jenkins/workspace/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000066fa0 sp=0xc000066f70 pc=0x45aaf3
runtime.bgscavenge(0x0?)
	/jenkins/workspace/go/src/runtime/mgcscavenge.go:633 +0x65 fp=0xc000066fc8 sp=0xc000066fa0 pc=0x45b0c5
runtime.gcenable.func2()
	/jenkins/workspace/go/src/runtime/mgc.go:179 +0x26 fp=0xc000066fe0 sp=0xc000066fc8 pc=0x451e26
runtime.goexit()
	/jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000066fe8 sp=0xc000066fe0 pc=0x4a7fe1
created by runtime.gcenable
	/jenkins/workspace/go/src/runtime/mgc.go:179 +0xaa

goroutine 34 [finalizer wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/jenkins/workspace/go/src/runtime/proc.go:381 +0xd6 fp=0xc000067e28 sp=0xc000067e08 pc=0x472976
runtime.runfinq()
	/jenkins/workspace/go/src/runtime/mfinal.go:193 +0x13d fp=0xc000067fe0 sp=0xc000067e28 pc=0x450ebd
runtime.goexit()
	/jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000067fe8 sp=0xc000067fe0 pc=0x4a7fe1
created by runtime.createfing
	/jenkins/workspace/go/src/runtime/mfinal.go:163 +0x45

goroutine 35 [syscall]:
syscall.Syscall6(0xc000182a30?, 0x67c2a5?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/jenkins/workspace/go/src/syscall/syscall_linux.go:91 +0x45 fp=0xc000182ab8 sp=0xc000182a30 pc=0x530fc5
os.(*Process).blockUntilWaitable(0xc000144300)
	/jenkins/workspace/go/src/os/wait_waitid.go:32 +0x9f fp=0xc000182b98 sp=0xc000182ab8 pc=0x577c5f
os.(*Process).wait(0xc000144300)
	/jenkins/workspace/go/src/os/exec_unix.go:22 +0x53 fp=0xc000182c20 sp=0xc000182b98 pc=0x56c5d3
os.(*Process).Wait(...)
	/jenkins/workspace/go/src/os/exec.go:132
os/exec.(*Cmd).Wait(0xc0001b0000)
	/jenkins/workspace/go/src/os/exec/exec.go:890 +0xc5 fp=0xc000182cd8 sp=0xc000182c20 pc=0x67e0c5
os/exec.(*Cmd).Run(0xb?)
	/jenkins/workspace/go/src/os/exec/exec.go:590 +0x65 fp=0xc000182d18 sp=0xc000182cd8 pc=0x67c105
os/exec.(*Cmd).CombinedOutput(0xc0001b0000)
	/jenkins/workspace/go/src/os/exec/exec.go:1005 +0x20a fp=0xc000182d90 sp=0xc000182d18 pc=0x67f10a
github.com/dremio/dremio-diagnostic-collector/cmd/local/jvmcollect.(*ttop).GetClasspath(0xc0001340f0, 0x18?)
	/jenkins/workspace/dremio-diagnostic-collector/cmd/local/jvmcollect/ttopcollect.go:80 +0x247 fp=0xc000182ed8 sp=0xc000182d90 pc=0xa74687
github.com/dremio/dremio-diagnostic-collector/cmd/local.runCollectClusterStats(0xc00017e1c0)
	/jenkins/workspace/dremio-diagnostic-collector/cmd/local/local.go:376 +0x152 fp=0xc000183008 sp=0xc000182ed8 pc=0xa99df2
github.com/dremio/dremio-diagnostic-collector/cmd/local.collect(0xc00017e1c0)
	/jenkins/workspace/dremio-diagnostic-collector/cmd/local/local.go:257 +0x2dd2 fp=0xc000183340 sp=0xc000183008 pc=0xa97f32
github.com/dremio/dremio-diagnostic-collector/cmd/local.Execute({0xc00011f598, 0x0, 0x0}, 0xe?)
	/jenkins/workspace/dremio-diagnostic-collector/cmd/local/local.go:526 +0x6b7 fp=0xc000183570 sp=0xc000183340 pc=0xa9c8f7
github.com/dremio/dremio-diagnostic-collector/cmd/awselogs.Execute({0xc00013cb13, 0xd}, {0xc000144180, 0x27}, {0xc000144270, 0x28})
	/jenkins/workspace/dremio-diagnostic-collector/cmd/awselogs/awselogs.go:99 +0x1073 fp=0xc000183c18 sp=0xc000183570 pc=0xaa2893
github.com/dremio/dremio-diagnostic-collector/cmd/awselogs_test.TestAWSELogs(0xc00010d520)
	/jenkins/workspace/dremio-diagnostic-collector/cmd/awselogs/aweslogs_test.go:53 +0x50b fp=0xc000183ea8 sp=0xc000183c18 pc=0xaa660b
testing.tRunner(0xc00010d520, 0xd1db10)
	/jenkins/workspace/go/src/testing/testing.go:1576 +0x217 fp=0xc000183fb0 sp=0xc000183ea8 pc=0x633397
testing.(*T).Run.func1()
	/jenkins/workspace/go/src/testing/testing.go:1629 +0x48 fp=0xc000183fe0 sp=0xc000183fb0 pc=0x634ea8
runtime.goexit()
	/jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000183fe8 sp=0xc000183fe0 pc=0x4a7fe1
created by testing.(*T).Run
	/jenkins/workspace/go/src/testing/testing.go:1629 +0x806

goroutine 36 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/jenkins/workspace/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001c1f50 sp=0xc0001c1f30 pc=0x472976
runtime.gcBgMarkWorker()
	/jenkins/workspace/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0001c1fe0 sp=0xc0001c1f50 pc=0x453bf1
runtime.goexit()
	/jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001c1fe8 sp=0xc0001c1fe0 pc=0x4a7fe1
created by runtime.gcBgMarkStartWorkers
	/jenkins/workspace/go/src/runtime/mgc.go:1199 +0x25

goroutine 37 [GC worker (idle)]:
runtime.gopark(0x63681493fb?, 0x0?, 0x0?, 0x0?, 0x0?)
	/jenkins/workspace/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001c0f50 sp=0xc0001c0f30 pc=0x472976
runtime.gcBgMarkWorker()
	/jenkins/workspace/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0001c0fe0 sp=0xc0001c0f50 pc=0x453bf1
runtime.goexit()
	/jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001c0fe8 sp=0xc0001c0fe0 pc=0x4a7fe1
created by runtime.gcBgMarkStartWorkers
	/jenkins/workspace/go/src/runtime/mgc.go:1199 +0x25

goroutine 50 [GC worker (idle)]:
runtime.gopark(0x636823b0bc?, 0x0?, 0x0?, 0x0?, 0x0?)
	/jenkins/workspace/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001bff50 sp=0xc0001bff30 pc=0x472976
runtime.gcBgMarkWorker()
	/jenkins/workspace/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0001bffe0 sp=0xc0001bff50 pc=0x453bf1
runtime.goexit()
	/jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001bffe8 sp=0xc0001bffe0 pc=0x4a7fe1
created by runtime.gcBgMarkStartWorkers
	/jenkins/workspace/go/src/runtime/mgc.go:1199 +0x25

goroutine 51 [GC worker (idle)]:
runtime.gopark(0x6367a2e529?, 0x0?, 0x0?, 0x0?, 0x0?)
	/jenkins/workspace/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001bef50 sp=0xc0001bef30 pc=0x472976
runtime.gcBgMarkWorker()
	/jenkins/workspace/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0001befe0 sp=0xc0001bef50 pc=0x453bf1
runtime.goexit()
	/jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001befe8 sp=0xc0001befe0 pc=0x4a7fe1
created by runtime.gcBgMarkStartWorkers
	/jenkins/workspace/go/src/runtime/mgc.go:1199 +0x25

goroutine 3 [runnable]:
runtime.slicecopy(0xc00208a000?, 0x1000?, 0xc00235c800?, 0x800?, 0x1?)
	/jenkins/workspace/go/src/runtime/slice.go:310 +0x105 fp=0xc0001bac90 sp=0xc0001bac88 pc=0x48a1e5
bytes.growSlice({0xc00235c800, 0x800, 0x800}, 0x200)
	/jenkins/workspace/go/src/bytes/buffer.go:241 +0x14e fp=0xc0001bad50 sp=0xc0001bac90 pc=0x5a42ee
bytes.(*Buffer).grow(0xc0001231a0, 0x200)
	/jenkins/workspace/go/src/bytes/buffer.go:142 +0x2bb fp=0xc0001badd0 sp=0xc0001bad50 pc=0x5a387b
bytes.(*Buffer).ReadFrom(0xc0001231a0, {0xdbe360, 0xc0001300d8})
	/jenkins/workspace/go/src/bytes/buffer.go:200 +0x66 fp=0xc0001bae38 sp=0xc0001badd0 pc=0x5a3f66
io.copyBuffer({0xdbdaa0, 0xc0001231a0}, {0xdbe360, 0xc0001300d8}, {0x0, 0x0, 0x0})
	/jenkins/workspace/go/src/io/io.go:413 +0x1c6 fp=0xc0001baee0 sp=0xc0001bae38 pc=0x51d286
io.Copy(...)
	/jenkins/workspace/go/src/io/io.go:386
os/exec.(*Cmd).writerDescriptor.func1()
	/jenkins/workspace/go/src/os/exec/exec.go:560 +0x65 fp=0xc0001baf50 sp=0xc0001baee0 pc=0x67c045
os/exec.(*Cmd).Start.func2(0xc00015c100)
	/jenkins/workspace/go/src/os/exec/exec.go:717 +0x43 fp=0xc0001bafb8 sp=0xc0001baf50 pc=0x67d463
os/exec.(*Cmd).Start.func3()
	/jenkins/workspace/go/src/os/exec/exec.go:729 +0x48 fp=0xc0001bafe0 sp=0xc0001bafb8 pc=0x67d3e8
runtime.goexit()
	/jenkins/workspace/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001bafe8 sp=0xc0001bafe0 pc=0x4a7fe1
created by os/exec.(*Cmd).Start
	/jenkins/workspace/go/src/os/exec/exec.go:716 +0xf8f

rax    0xca
rbx    0x0
rcx    0x4aa623
rdx    0x0
rdi    0x10bb608
rsi    0x80
rbp    0x7ffc8b95b7a8
rsp    0x7ffc8b95b760
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x7ffc8b95b7d8
r13    0x3
r14    0x10baee0
r15    0x106e9a0
rip    0x4aa621
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

**Comment by rsvihladremio** [comment]
none of my code involved here, this is looking like gc??

SIGQUIT: quit
PC=0x43d80e m=0 sigcode=0

goroutine 0 [idle]:
runtime/internal/syscall.Syscall6()
	/jenkins/workspace/go/src/runtime/internal/syscall/asm_linux_amd64.s:36 +0xe fp=0x7ffdff81fe80 sp=0x7ffdff81fe78 pc=0x43d80e
runtime/internal/syscall.EpollWait(0x27010f80?, {0x7ffdff81ff48?, 0x270104f0?, 0x0?}, 0xff81ff64?, 0x7ffd?)
	/jenkins/workspace/go/src/runtime/internal/syscall/syscall_linux.go:55 +0x45 fp=0x7ffdff81fed0 sp=0x7ffdff81fe80 pc=0x43d785
runtime.netpoll(0xc00003e000?)
	/jenkins/workspace/go/src/runtime/netpoll_epoll.go:118 +0xcb fp=0x7ffdff820560 sp=0x7ffdff81fed0 pc=0x46f70b
runtime.findRunnable()
	/jenkins/workspace/go/src/runtime/proc.go:3191 +0x825 fp=0x7ffdff820670 sp=0x7ffdff820560 pc=0x47b9a5
runtime.schedule()
	/jenkins/workspace/go/src/runtime/proc.go:3582 +0xb1 fp=0x7ffdff8206a8 sp=0x7ffdff820670 pc=0x47cb11
runtime.park_m(0xc00008b860?)
	/jenkins/workspace/go/src/runtime/proc.go:3745 +0x11f fp=0x7ffdff8206f0 sp=0x7ffdff8206a8 pc=0x47d01f
traceback: unexpected SPWRITE function runtime.mcall
runtime.mcall()
	/jenkins/workspace/go/src/runtime/asm_amd64.s:458 +0x4e fp=0x7ffdff820708 sp=0x7ffdff8206f0 pc=0x4a99ee

goroutine 1 [syscall]:
runtime.racefini()
	/jenkins/workspace/go/src/runtime/race.go:417 +0x1b fp=0xc0000f7e70 sp=0xc0000f7e38 pc=0x48545b
os.runtime_beforeExit(0x0)
	/jenkins/workspace/go/src/runtime/proc.go:304 +0x2a fp=0xc0000f7e88 sp=0xc0000f7e70 pc=0x4a670a
os.Exit(0x0)
	/jenkins/workspace/go/src/os/proc.go:75 +0x3a fp=0xc0000f7ea8 sp=0xc0000f7e88 pc=0x56fd7a
main.main()
	_testmain.go:95 +0x2ea fp=0xc0000f7f40 sp=0xc0000f7ea8 pc=0xaf3dca
runtime.main()
	/jenkins/workspace/go/src/runtime/proc.go:267 +0x2bb fp=0xc0000f7fe0 sp=0xc0000f7f40 pc=0x47619b
runtime.goexit()
	/jenkins/workspace/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000f7fe8 sp=0xc0000f7fe0 pc=0x4ab9e1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x1132150?, 0x117b960?, 0x0?, 0x0?, 0x0?)
	/jenkins/workspace/go/src/runtime/proc.go:398 +0xce fp=0xc0000527a8 sp=0xc000052788 pc=0x47660e
runtime.goparkunlock(...)
	/jenkins/workspace/go/src/runtime/proc.go:404
runtime.forcegchelper()
	/jenkins/workspace/go/src/runtime/proc.go:322 +0xb3 fp=0xc0000527e0 sp=0xc0000527a8 pc=0x476473
runtime.goexit()
	/jenkins/workspace/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000527e8 sp=0xc0000527e0 pc=0x4ab9e1
created by runtime.init.6 in goroutine 1
	/jenkins/workspace/go/src/runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/jenkins/workspace/go/src/runtime/proc.go:398 +0xce fp=0xc000062f78 sp=0xc000062f58 pc=0x47660e
runtime.goparkunlock(...)
	/jenkins/workspace/go/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
	/jenkins/workspace/go/src/runtime/mgcsweep.go:280 +0x94 fp=0xc000062fc8 sp=0xc000062f78 pc=0x460734
runtime.gcenable.func1()
	/jenkins/workspace/go/src/runtime/mgc.go:200 +0x25 fp=0xc000062fe0 sp=0xc000062fc8 pc=0x455925
runtime.goexit()
	/jenkins/workspace/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000062fe8 sp=0xc000062fe0 pc=0x4ab9e1
created by runtime.gcenable in goroutine 1
	/jenkins/workspace/go/src/runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000036070?, 0xe2e510?, 0x1?, 0x0?, 0xc0000071e0?)
	/jenkins/workspace/go/src/runtime/proc.go:398 +0xce fp=0xc000068f70 sp=0xc000068f50 pc=0x47660e
runtime.goparkunlock(...)
	/jenkins/workspace/go/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x117af60)
	/jenkins/workspace/go/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc000068fa0 sp=0xc000068f70 pc=0x45e029
runtime.bgscavenge(0x0?)
	/jenkins/workspace/go/src/runtime/mgcscavenge.go:653 +0x3c fp=0xc000068fc8 sp=0xc000068fa0 pc=0x45e59c
runtime.gcenable.func2()
	/jenkins/workspace/go/src/runtime/mgc.go:201 +0x25 fp=0xc000068fe0 sp=0xc000068fc8 pc=0x4558c5
runtime.goexit()
	/jenkins/workspace/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000068fe8 sp=0xc000068fe0 pc=0x4ab9e1
created by runtime.gcenable in goroutine 1
	/jenkins/workspace/go/src/runtime/mgc.go:201 +0xa5

goroutine 18 [finalizer wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/jenkins/workspace/go/src/runtime/proc.go:398 +0xce fp=0xc000104e28 sp=0xc000104e08 pc=0x47660e
runtime.runfinq()
	/jenkins/workspace/go/src/runtime/mfinal.go:193 +0x13b fp=0xc000104fe0 sp=0xc000104e28 pc=0x45499b
runtime.goexit()
	/jenkins/workspace/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000104fe8 sp=0xc000104fe0 pc=0x4ab9e1
created by runtime.createfing in goroutine 1
	/jenkins/workspace/go/src/runtime/mfinal.go:163 +0x3d

rax    0xfffffffffffffffc
rbx    0x4
rcx    0x43d80e
rdx    0x80
rdi    0x4
rsi    0x7ffdff81ff48
rbp    0x7ffdff81fec0
rsp    0x7ffdff81fe78
r8     0x0
r9     0x0
r10    0x927b8
r11    0x246
r12    0x7ffdff81ff50
r13    0x117b960
r14    0x117b340
r15    0x45
rip    0x43d80e
rflags 0x246
cs     0x33
fs     0x0
gs     0x0

**Comment by rsvihladremio** [comment]
the failure is in a different spot every time, HOWEVER, it does appear to be a real change in the code and not environmental, I set the build server to build 0.7.4 and it passes happily

Tried to remove

* findCluster logic
* mutexs and printing around consoleprint
* lots of log init calls (this was for the better though)

Last thing I an think of is maybe the ticker code as I have seen everyone once in awhile errors around this, it is interesting I cannot reproduce this on windows or linux locally

**Comment by rsvihladremio** [comment]
backing out all changes on a development branch and slowly adding them back via cherry pick

**Comment by rsvihladremio** [comment]
ok tracked it down right away, had a silly bit of code that was using sjk to track classpath so I moved initialization to a common constructor and I had missed the bit where sjk is deleted. This leads to a race where depending on order of execution the method to get classpath may have the jar yanked out from under it, flipped this code out and the weird errors stopped

 ```
func NewTtopService() (TtopService, error) {
	t := &ttop{}
	tmpDir, err := os.MkdirTemp("", "ddc-sjk")
	if err != nil {
		return &ttop{}, err
	}
	t.tmpDir = tmpDir
	// referencing a part interior to go always use / path
	data, err := fs.ReadFile(f, "lib/sjk.jar")
	if err != nil {
		return &ttop{}, err
	}

	sjk := filepath.Join(t.tmpDir, "sjk.jar")
	if err := os.WriteFile(sjk, data, 0600); err != nil {
		return &ttop{}, err
	}
	t.sjk = sjk
	return t, nil
}

	t.mu.Lock()
	defer t.mu.Unlock()
	if t.tmpDir == "" {
		return "", errors.New("unable to get data from ttop as it is not yet started")
	}
	if err := os.RemoveAll(t.tmpDir); err != nil {
		simplelog.Warningf("must remove manually directory %v where sjk.jar is installed due to error: '%v'", t.tmpDir, err)
	}
	t.tmpDir = ""
```
